version: '3'
services:
  frontend:
    image: cardotisler/dswarm-frontend:1.0.0
    ports:
      - "5173:5173"
    networks:
      - docker-swarm-network

  backend:
    image: cardotisler/dswarm-backend:1.0.0
    env_file:
      - .env-db
    ports:
      - "3001:3001"
    networks:
      - docker-swarm-network

  db:
    image: mysql/mysql-server:5.7
    env_file:
      - .env-db
    volumes:
      - "./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - "3306:3306"
    networks:
      - docker-swarm-network

  monitor:
    image: dockersamples/visualizer
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - docker-swarm-network

networks:
  docker-swarm-network: