version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - docker-swarm-network

  backend:
    build: ./backend
    env_file:
      - .env-db
    ports:
      - "3001:3001"
    networks:
      - docker-swarm-network

  db:
    build: ./backend/db
    env_file:
      - .env-db
    volumes:
      - "./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - "3306:3306"
    networks:
      - docker-swarm-network

networks:
  docker-swarm-network: